Feature/get-datasets PLUM-7 / PLUM-6 / PLUM-9
DHI-GRAS/terracotta-react pull request #4
Opened 2021-11-11 14:47 UTC by bertearazvan

This PR aims to add the `getDatasets` method as part of the context and the useTerracotta hook.

2021-11-11 15:34 UTC, brigittarucz approved these changes

2021-11-12 09:14 UTC, rihr approved these changes

2021-11-17 13:50 UTC, j08lue requested changes
Nice, great quality of the docs, for what I can judge.

I think we are missing a brief initial statement about, what Terracotta is, and why you would want to use this package for integrating Terracotta into your react web map application.

Also, please include a link to the Terracotta repo and maybe also the TC logo (not sure about latter, up to you)?

2021-11-22 09:05 UTC, rihr approved these changes
Meant to request review just from me, by the way?

2021-11-22 09:05 UTC, rihr commented on README.md
> +- It includes built-in Typescript definitions, therefore, it prevents unpredictable type errors when used in your app. The types are available by importing them from the package.
```suggestion
- Abstracts away the logic around what endpoints you should hit to get the right datasets and display them on a map. All of it through a friendly API.
- Uses the highly performant [Deck.gl](https://deck.gl/) based on the WebGL framework.
- Includes TypeScript definitions, therefore, it prevents unpredictable type errors when used in your app. The types are available by importing them from the package.
```

2021-11-25 13:55 UTC, j08lue approved these changes

2021-11-25 14:03 UTC, merged